### ISSUE TITLE
QuickBlox RN SDK Fails Play Store Upload Due to 16 KB Page Size Incompatibility

### ISSUE THREAD

**Issue by Rajat1Ggc** [QuickBlox/quickblox-react-native-sdk#85]
<h1>Issue:</h1>
While uploading our Android app to the Google Play Store, the Play Console blocks the submission due to native libraries not supporting the 16 KB memory page size requirement (mandatory for Android 15 and new Play Store policies).

This issue appears to come from several native libraries bundled through the QuickBlox React Native SDK or dependencies that the SDK still uses (Hermes, FBJNI, JSI, Reanimated, ImagePipeline, MMKV, etc.).

Because of this, our production build cannot be uploaded to the Play Store.

<h2>⚠️ Play Console Error</h2>
The Play Store reports the following libraries as incompatible:

base/lib/arm64-v8a/libc++_shared.so
base/lib/arm64-v8a/libfbjni.so
base/lib/arm64-v8a/libhermes.so
base/lib/arm64-v8a/libhermestooling.so
base/lib/arm64-v8a/libimagepipeline.so
base/lib/arm64-v8a/libjsi.so
base/lib/arm64-v8a/libnative-filters.so
base/lib/arm64-v8a/libnative-imagetranscoder.so
base/lib/arm64-v8a/libreactnative.so
base/lib/arm64-v8a/libreactnativemmkv.so
base/lib/arm64-v8a/libreanimated.so
base/lib/arm64-v8a/librnscreens.so
base/lib/arm64-v8a/libworklets.so

(and x86_64 variants)
These appear to be compiled with an outdated NDK configuration that does not support 16 KB pages.

<h3>🔍 What We Tried</h3>
Updating React Native (not possible due to QuickBlox dependency constraints)
Updating MMKV / Reanimated / Hermes (conflicts with QuickBlox version)
Rebuilding the app with latest NDK
None resolve the issue because the root libraries are coming from dependencies included in QuickBlox RN SDK.

<h3>🚩 Impact</h3>
This issue blocks Play Store submission, making it impossible to publish updates for apps integrating QuickBlox.

<h3>❓ Request</h3>
Is a QuickBlox React Native SDK update planned with libraries rebuilt for 16 KB page size support?
If yes, is there an ETA?
If not, could you provide temporary workarounds or guidance?
This is a critical blocker for production releases.

<h3>Environment</h3>
QuickBlox React Native SDK version: (your version)
<br/>
React Native version: (your version)<br/>
Android NDK: (your version)<br/>
Build type: Release (AAB)<br/>
Platform: Android

<img width="983" height="741" alt="Image" src="https://github.com/user-attachments/assets/ba9cf57f-3f93-4a1f-aa81-99fab4bad6b1" />

**Comment by hiteshgarg123** [comment]
Hello @Rajat1Ggc,
I’m Hitesh, PM at QuickBlox 👋

We’re aware of this issue and have fixed it in our latest React Native SDK release.
Please update your project to QuickBlox React Native SDK v0.12.4, which should resolve the problem.

🔗 [Release v0.12.4](https://github.com/QuickBlox/quickblox-react-native-sdk/releases/tag/0.12.4)

If you still encounter the issue after updating, please try clearing Gradle caches and rebuild the project using the following steps:

Run the following commands in the terminal:

1. Clear global Gradle cache

```
cd

rm -rf ~/.gradle
```

2. Clean project-level Gradle and build files

```
rm -rf android/app/.cxx
rm -rf android/.gradle
rm -rf android/build
```
Then rebuild your project as usual.

Let me know if the issue persists after following these steps — we’ll be happy to help further.

**Comment by Rajat1Ggc** [comment]
Hi @hiteshgarg123 , thanks for your quick response

I updated to **QuickBlox React Native SDK v0.12.4** as suggested, and also cleared all Gradle caches:

rm -rf ~/.gradle
rm -rf android/app/.cxx
rm -rf android/.gradle
rm -rf android/build


Then rebuilt the entire project.

Unfortunately, the issue still persists.

**1. Play Store is still flagging the same native libraries**

After upgrading to v0.12.4, the Play Console still reports the exact same list of incompatible native libraries (React Native, Hermes, Reanimated, MMKV, FBJNI, etc.) that do not support the 16 KB memory page size.

So the SDK update did NOT update/fix the native dependencies.

**2. iOS build started failing after upgrading**

In addition, updating to v0.12.4 causes new iOS build errors.
(If needed, I can provide the full error logs.)

Because of this, I had to revert the version to make iOS work again.


The issue is not QuickBlox’s library itself, but the fact that the QuickBlox RN SDK is still using outdated React Native core dependencies (Hermes, React-Fresco, JSI, MMKV, Reanimated, Screens, etc.). These libraries are still compiled with old NDK configurations that do not support the Play Store requirement.

Therefore upgrading QuickBlox to v0.12.4 did not resolve the 16 KB page-size compliance issue.

**Comment by IlliaChemolosov** [comment]
Hello @Rajat1Ggc, 

Thank you for sharing the details. Based on your description, we do not see any indications of issues originating from our SDK. As a reminder, our SDK depends on React Native, specified as:

```
"peerDependencies": {
  "react-native": ">=0.61.0"
}

```
This means it supports React Native version 0.61.0 and higher. According to React Native release notes, support for a 16KB page size begins with version 0.77+. From this, it seems that updating the React Native version in your application could help resolve the issue.

Since the React Native version in use was not specified, we recommend verifying that it is up to date. If there is any specific behavior you believe originates from our SDK, please let us know so we can investigate further.

Thank you for your cooperation.
